import { useState } from 'react'

export const DISCLAIMER_POINTS = [
  'DigiPat is an educational tool for practising clinical communication and OSCE-style stations. It is intended for training and simulation only.',
  'It is NOT a medical device. It does not diagnose, treat or give advice about real people, and must not be used for real patient care or clinical decisions.',
  'All patients and cases are fictional. Do not enter real patient information or any personal health data.',
  'The simulated patient and the feedback are generated by an AI model running on this Mac. They can be wrong, inconsistent or incomplete. Feedback is formative and is not an examiner’s judgement.',
  'Some stations cover sensitive topics such as suicide, self-harm and substance use. If you are personally affected, please seek support from local emergency services or a crisis line.',
  'Everything runs offline on your Mac. After the one-time model download, nothing you type leaves this computer.'
]

export function Onboarding({ onAccept }: { onAccept: () => void }): React.JSX.Element {
  const [checked, setChecked] = useState(false)
  return (
    <div className="flex h-full items-center justify-center overflow-y-auto p-8">
      <div className="card max-w-2xl space-y-5 p-8">
        <div className="drag -mt-2 h-4" />
        <h1 className="text-2xl font-semibold">Welcome to DigiPat</h1>
        <p className="text-sm text-stone-600 dark:text-stone-300">
          A free, offline OSCE practice simulator. Please read the following before you start.
        </p>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed">
          {DISCLAIMER_POINTS.map((p) => (
            <li key={p}>{p}</li>
          ))}
        </ul>
        <label className="flex items-start gap-3 rounded-lg bg-stone-100 p-3 text-sm dark:bg-stone-800">
          <input
            type="checkbox"
            className="mt-0.5 h-4 w-4 accent-brand-600"
            checked={checked}
            onChange={(e) => setChecked(e.target.checked)}
          />
          <span>
            I understand that this is an educational simulation, not a medical device, and that I must not use it
            for real patients or enter real patient data.
          </span>
        </label>
        <div className="flex justify-end">
          <button className="btn-primary" disabled={!checked} onClick={onAccept}>
            Continue
          </button>
        </div>
      </div>
    </div>
  )
}
